version: '2'
services:
  db:
    image: mysql/mysql-server:latest
    ports:
      - "6603:3306"
    environment:
      MYSQL_ROOT_PASSWORD: supergeheim
      MYSQL_USER: mosaik
      MYSQL_PASSWORD: nochgeheimer
      MYSQL_DATABASE: mosaiktest